#!/bin/bash
# error checking
if [ $# != 2 ]
then
    cat <<EOF
Usage rclonemount volume mount_point
EOF
    exit 1
fi

if which rclone >/dev/null
then
    true
else
   echo Can\'t find rclone, exiting.
   exit 3
fi

if [ ! -d "$2" ]
then
    echo Mount point $2 does not exist.
    exit 2
fi

VOL="$1"
DIR="$2"

# Check if getting something out of the dir fails
# if so, maybe a stale mount so try to unmount
if ! ls "$DIR/." >/dev/null
then
   fusermount -u "$DIR"
fi
# See if directory appears to be mounted. If so, we are done
if grep "$DIR" /etc/mtab >/dev/null
then
  echo $VOL Mounted
else  # if not, mount it
  echo Mounting $VOL
  rclone mount --vfs-cache-mode full "$VOL"/ "$DIR" &  # run in background
fi
exit 0  # we tried
