#!/bin/bash
# Usage:
# singleexec "title" command
# Search for window with title and activate or start command
if xdotool search --limit 1 --name "$1" windowmap windowactivate
then
 exit 0
else
  shift
  exec "$@"
fi  
